[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "richpool"
version = "0.1.0"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
keywords = ["rich", "progress bar", "parallel", "multiprocessing"]
authors = [{ name = "Sahil Jhawar" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pathos>=0.3.0",
    "rich>=13.0.0",
    "joblib",
    "pytest",
    "ty",
    "ruff",
]

[project.optional-dependencies]
mpi = ["mpi4py"]
docs = [
    "sphinx",
    "pydata-sphinx-theme",
    "myst-parser",
    "sphinx-exec-code",
    "sphinx_copybutton",
    "matplotlib>=3.11.1",
    "emcee>=3.1.6",
    "sphinx-github-changelog",
]

[project.urls]
Homepage = "https://github.com/sahiljhawar/richpool"
Documentation = "https://richpool.readthedocs.io/en/latest/"
Download = "https://pypi.org/project/richpool/#files"
Tracker = "https://github.com/sahiljhawar/richpool/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--verbose -ra"

[tool.coverage.run]
omit = ["src/richpool/mpi.py"]

[tool.bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "version: bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"']
"src/richpool/__init__.py" = ['__version__ = "{version}"']
